name: amazon-sentinel

include:
  - path: supabase/docker/docker-compose.yml
    env_file: .env

services:
  backend:
    build: ./backend
    container_name: sentinel-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - SUPABASE_URL=http://kong:8000
      - SUPABASE_SERVICE_KEY=${SERVICE_ROLE_KEY}
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: sentinel-frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_SUPABASE_URL=http://localhost:8000
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
    depends_on:
      - backend